name: Development

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # add a step to checkout the code
    - uses: actions/checkout@v2

    # add a step to install .NET SDK 7
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    # add a step to restore NuGet packages
    - name: Restore NuGet Packages
      run: dotnet restore
    
    # add a step to build the solution
    - name: Build
      run: dotnet build --configuration Release
    
    # add a step to test the solution
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    # add a step to publish src/WebApi
    - name: Publish
      run: dotnet publish src/WebApi --configuration Release --output publish
    
    # add a step to login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web apps
    - name: Azure WebApp Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: publish
